"""The cleaning rulebook: every rule is plain code, never generated by an LLM.

From Phase 1 on, the LLM may only *propose* a list of rule ids and parameters;
execution stays here so the same input always produces the same output.

Two properties matter more than the rules themselves:

* **Order is fixed and declared.** RULE_ORDER, not the caller, decides the
  sequence. Trimming after casting would produce a different result from casting
  after trimming, and a caller-controlled order would break criterion S1.
* **Nothing is lost silently.** A value that fails to convert is written to the
  diff log with its row index, never quietly replaced by null.
"""

from __future__ import annotations

import math
import re
import unicodedata
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass, field
from typing import Final

import pandas as pd

from analysis_system.services.vietnamese_text import (
    canonical_forms,
    number_from_words,
)

MISSING_FLAG_COLUMN: Final[str] = "_missing_required"

# Execution order. Text normalisation first, so the parsers downstream see clean
# strings; de-duplication after normalisation, so values that differ only by
# whitespace collapse together; the missing-value flag last, so it sees the
# final state of the frame.
RULE_ORDER: Final[tuple[str, ...]] = (
    "trim_whitespace",
    "normalize_unicode_nfc",
    # Before the parsers: a sentinel has to become missing while it is still
    # text, so casting never sees it and never reports it as a failed value.
    "replace_sentinel_with_null",
    # Sau khi chu da sach, truoc khi bat dau doc nghia: gop bien the phai thay
    # chu da cat khoang trang va thong nhat dau, con doi so viet bang chu thi
    # phai xong TRUOC cast_numeric_safe - no ghi ra chu so de luat kia ep kieu.
    "merge_text_variants",
    "cast_words_to_numbers",
    "standardize_datetime",
    "cast_numeric_safe",
    "drop_exact_duplicates",
    # Last, so it sees the sentinels the rule above turned into real nulls.
    "flag_missing_required",
)


# What each rule actually reads. Anything else is refused by name rather than
# dropped in silence, so a proposal can never promise behaviour the code has not
# got.
# How much of a column has to cast before it counts as a number column held as
# text. The same bar `statistics._kinds` uses to decide the same thing, because
# two answers to one question is one answer too many.
NUMERIC_SHARE: Final[float] = 0.9

# Mot cot chi co dung mot gia tri thi khong doi so viet bang chu: "nam" lap lai
# tu tren xuong duoi nhieu kha nang la chu, khong phai so 5.
MIN_DISTINCT: Final[int] = 2

RULE_PARAMS: Final[Mapping[str, frozenset[str]]] = {
    "trim_whitespace": frozenset(),
    "normalize_unicode_nfc": frozenset(),
    "replace_sentinel_with_null": frozenset({"sentinels"}),
    "standardize_datetime": frozenset({"assume_timezone"}),
    "cast_numeric_safe": frozenset(),
    "merge_text_variants": frozenset(),
    "cast_words_to_numbers": frozenset(),
    "drop_exact_duplicates": frozenset(),
    "flag_missing_required": frozenset(),
}


class RuleError(RuntimeError):
    """A rule was asked to do something it must not guess its way through."""


@dataclass(frozen=True)
class DiffEntry:
    """One recorded change or refusal, traceable to a single cell or row."""

    rule_id: str
    column: str
    row_index: int
    before: str
    after: str
    reason: str


@dataclass(frozen=True)
class RuleSpec:
    """A rule the Manager approved, with the parameters it may use."""

    rule_id: str
    columns: tuple[str, ...] = ()
    params: Mapping[str, object] = field(default_factory=dict)


@dataclass(frozen=True)
class CleanOutcome:
    """The result of running a plan of rules over a frame."""

    frame: pd.DataFrame
    diff: tuple[DiffEntry, ...]
    rows_in: int
    rows_out: int
    rules_applied: tuple[str, ...]

    @property
    def rows_dropped_pct(self) -> float:
        """Percentage of input rows removed. Phase 1 halts above 5 percent."""
        if self.rows_in == 0:
            return 0.0
        return 100.0 * (self.rows_in - self.rows_out) / self.rows_in


def _target_columns(spec: RuleSpec, frame: pd.DataFrame) -> tuple[str, ...]:
    """Return the columns a rule applies to, checking that they all exist."""
    if not spec.columns:
        return tuple(str(column) for column in frame.columns)
    missing = [column for column in spec.columns if column not in frame.columns]
    if missing:
        raise RuleError(f"Rule {spec.rule_id!r} tro toi cot khong ton tai: {missing}")
    return spec.columns


def _require_str_param(spec: RuleSpec, name: str) -> str:
    """Read a mandatory string parameter, refusing to fall back to a default."""
    value = spec.params.get(name)
    if not isinstance(value, str) or not value:
        raise RuleError(
            f"Rule {spec.rule_id!r} thieu tham so bat buoc {name!r}. "
            "Khong duoc doan gia tri mac dinh."
        )
    return value


def _as_text(value: object) -> str:
    """Render a cell for the diff log, collapsing every missing marker to blank."""
    if value is None or value is pd.NaT or value is pd.NA:
        return ""
    if isinstance(value, float) and math.isnan(value):
        return ""
    return str(value)


def trim_whitespace(frame: pd.DataFrame, spec: RuleSpec) -> tuple[pd.DataFrame, list[DiffEntry]]:
    """Strip leading and trailing whitespace from text columns."""
    result = frame.copy()
    diff: list[DiffEntry] = []
    for column in _target_columns(spec, frame):
        series = result[column]
        if series.dtype != object and not pd.api.types.is_string_dtype(series):
            continue
        stripped = series.astype("string").str.strip()
        changed = stripped.ne(series.astype("string")) & series.notna()
        for row_index in result.index[changed.fillna(False)]:
            diff.append(
                DiffEntry(
                    spec.rule_id,
                    column,
                    int(row_index),
                    _as_text(series[row_index]),
                    _as_text(stripped[row_index]),
                    "cat khoang trang thua",
                )
            )
        result[column] = stripped
    return result, diff


def normalize_unicode_nfc(
    frame: pd.DataFrame, spec: RuleSpec
) -> tuple[pd.DataFrame, list[DiffEntry]]:
    """Normalise text to Unicode NFC so equal strings compare equal."""
    result = frame.copy()
    diff: list[DiffEntry] = []
    for column in _target_columns(spec, frame):
        series = result[column]
        if series.dtype != object and not pd.api.types.is_string_dtype(series):
            continue
        normalised = series.map(
            lambda value: unicodedata.normalize("NFC", value) if isinstance(value, str) else value
        )
        for row_index in result.index:
            before, after = series[row_index], normalised[row_index]
            if isinstance(before, str) and before != after:
                diff.append(
                    DiffEntry(
                        spec.rule_id,
                        column,
                        int(row_index),
                        before,
                        str(after),
                        "chuan hoa Unicode NFC",
                    )
                )
        result[column] = normalised
    return result, diff


def replace_sentinel_with_null(
    frame: pd.DataFrame, spec: RuleSpec
) -> tuple[pd.DataFrame, list[DiffEntry]]:
    """Turn a stated sentinel value into a real missing value.

    Datasets encode "none" as 0 or a placeholder string all the time. Left as
    it is, every average over the column is wrong and no null check can see the
    problem, because the value is not null - it just means nothing.

    Two things must be stated and are never guessed:

    * which values are sentinels, because 0 is a real measurement in one column
      and a placeholder in the next;
    * which columns to touch, because applying this across a whole table would
      blank out legitimate zeros - a scale where 0 means "not waterfront" is
      data, not absence of data.

    Raises:
        RuleError: the sentinel values or the columns were not stated.
    """
    sentinels = spec.params.get("sentinels")
    if not isinstance(sentinels, list) or not sentinels:
        raise RuleError(
            f"Rule {spec.rule_id!r} bat buoc co tham so 'sentinels' la mot danh sach "
            "gia tri canh chung. Khong duoc doan."
        )
    if not spec.columns:
        raise RuleError(
            f"Rule {spec.rule_id!r} bat buoc chi ro cot. Ap len toan bang se xoa ca "
            "nhung so 0 hop le (vi du thang bac 0 nghia la khong sat mat nuoc)."
        )

    wanted = {str(value) for value in sentinels}
    result = frame.copy()
    diff: list[DiffEntry] = []
    for column in _target_columns(spec, frame):
        series = result[column]
        matches = series.astype("string").isin(wanted).fillna(False)
        flags = matches.to_numpy(dtype=bool)
        for row_index in result.index[flags]:
            diff.append(
                DiffEntry(
                    spec.rule_id,
                    column,
                    int(row_index),
                    _as_text(series.loc[row_index]),
                    "",
                    "gia tri canh chung -> rong",
                )
            )
        result[column] = series.where(~matches.astype(bool), other=None)
    return result, diff


def standardize_datetime(
    frame: pd.DataFrame, spec: RuleSpec
) -> tuple[pd.DataFrame, list[DiffEntry]]:
    """Parse mixed date formats into one UTC timestamp column.

    The timezone to assume for values that carry no offset must be given
    explicitly: guessing it silently shifts every downstream duration.

    Raises:
        RuleError: assume_timezone is missing, or the column mixes values with
            and without an offset, which cannot be resolved without a decision.
    """
    assume_timezone = _require_str_param(spec, "assume_timezone")
    result = frame.copy()
    diff: list[DiffEntry] = []
    for column in _target_columns(spec, frame):
        original = result[column]
        try:
            parsed = pd.to_datetime(original, errors="coerce", format="mixed")
        except (ValueError, TypeError) as exc:
            raise RuleError(
                f"Cot {column!r} tron lan gia tri co va khong co offset mui gio: {exc}"
            ) from exc
        if parsed.dt.tz is None:
            parsed = parsed.dt.tz_localize(assume_timezone)
        parsed = parsed.dt.tz_convert("UTC")

        failed = parsed.isna() & original.notna() & (original.astype("string") != "")
        for row_index in result.index[failed]:
            diff.append(
                DiffEntry(
                    spec.rule_id,
                    column,
                    int(row_index),
                    _as_text(original[row_index]),
                    "",
                    "khong parse duoc ngay gio",
                )
            )
        result[column] = parsed
    return result, diff


# So viet theo kieu Viet Nam: dau CHAM tach hang nghin. "2.000" la hai nghin.
#
# pandas doc "2.000" thanh 2.0. Ca cot deu viet kieu do thi 100% gia tri ep
# duoc, khong mot dong canh bao nao, va moi con so bi chia cho 1000. Do duoc
# tren mot cot tien nam dong: tong dung 141.750, he thong bao 141,75.
#
# Nhom dau khong duoc bat dau bang so 0: "0.370" la mot so thap phan lam tron,
# khong phai "0370". Khong co dieu kien nay thi chinh bang bankruptcy - toan gia
# tri dang 0.xxx - se bi tu choi oan.
# Hai dau cham tro len: khong con cach hieu nao khac ngoai nhom hang nghin.
MULTI_DOT: Final[int] = 2

GROUPED_THOUSANDS: Final[re.Pattern[str]] = re.compile(r"^-?[1-9]\d{0,2}(\.\d{3})+$")


def _thousand_grouped(values: pd.Series) -> str:
    """Cot nay co phai so nhom hang nghin kieu Viet khong, va vi sao nghi the.

    Returns:
        Ly do de tu choi, hoac rong. Rong la truong hop thuong gap.
    """
    text = [
        stripped
        for stripped in (str(value).strip() for value in values)
        if stripped and stripped.lower() != "nan"
    ]
    if not text:
        return ""

    grouped = [item for item in text if GROUPED_THOUSANDS.match(item)]
    if not grouped:
        return ""

    # Hai dau cham tro len thi khong con gi de ban: "1.234.567" khong the la mot
    # so thap phan.
    chac_chan = [item for item in grouped if item.count(".") >= MULTI_DOT]
    if chac_chan:
        return (
            f"cot nay viet so theo kieu Viet Nam - dau cham tach hang nghin "
            f"(vi du {chac_chan[0]!r}). Ep thang se chia moi con so cho 1000"
        )

    # Ca cot deu dang `n.000`. Khong phan biet duoc voi so ba chu so thap phan,
    # va doan sai o day thi sai gap 1000 lan - nen dung lai va hoi.
    if len(grouped) == len(text):
        return (
            f"cot nay co the viet so theo kieu Viet Nam - dau cham tach hang "
            f"nghin (vi du {grouped[0]!r}), hoac la so thap phan ba chu so. "
            f"Hai cach hieu lech nhau 1000 lan nen he thong khong tu doan"
        )
    return ""


def cast_numeric_safe(frame: pd.DataFrame, spec: RuleSpec) -> tuple[pd.DataFrame, list[DiffEntry]]:
    """Convert number columns held as text, and leave the rest alone.

    Named no columns, this rule sees every column in the table - so the question
    it has to answer first is which of them are numbers written as text. A
    column where the values do not cast is not a number column needing
    conversion; it is a column this rule has no business touching.

    That distinction was missing, and it cost two columns of a real table: a date
    column and a channel column became `NaN` from top to bottom. Every one of
    those losses was written to the diff log, exactly as promised - and
    **recording the destruction of a column is not the same as not destroying
    it**.

    A value that fails inside a column that is otherwise numeric is still
    recorded with its row index, as before. It must never become null without a
    trace.
    """
    result = frame.copy()
    diff: list[DiffEntry] = []
    for column in _target_columns(spec, frame):
        original = result[column]
        present = original.notna() & (original.astype("string") != "")
        converted = pd.to_numeric(original, errors="coerce")
        failed = converted.isna() & present

        # Hoi TRUOC khi ep: mot cot bi hieu sai kieu nay van ep duoc 100%, nen
        # ty le thanh cong khong bat duoc no. Im lang o day la sai gap 1000 lan.
        grouped = _thousand_grouped(original[present])
        if grouped:
            diff.append(
                DiffEntry(spec.rule_id, str(column), -1, "giu nguyen", "giu nguyen", grouped)
            )
            continue

        readable = int(present.sum())
        casts = readable - int(failed.sum())
        if readable and casts / readable < NUMERIC_SHARE:
            # Not a number column. Left as it was, and said so - a column
            # skipped in silence reads exactly like a column nobody considered.
            diff.append(
                DiffEntry(
                    spec.rule_id,
                    str(column),
                    -1,
                    "giu nguyen",
                    "giu nguyen",
                    f"chi {casts}/{readable} gia tri ep duoc ve so - cot nay khong phai "
                    f"cot so, ep se xoa sach no",
                )
            )
            continue

        for row_index in result.index[failed]:
            diff.append(
                DiffEntry(
                    spec.rule_id,
                    str(column),
                    int(row_index),
                    _as_text(original[row_index]),
                    "",
                    "khong ep duoc ve so",
                )
            )
        result[column] = converted
    return result, diff


def _numeric_share(values: pd.Series) -> float:
    """Ty le o doc duoc thanh so. Mot cot so dang luu dang chu thi gan bang 1."""
    readable = int(values.notna().sum())
    if not readable:
        return 0.0
    return float(pd.to_numeric(values, errors="coerce").notna().sum()) / readable


def merge_text_variants(
    frame: pd.DataFrame, spec: RuleSpec
) -> tuple[pd.DataFrame, list[DiffEntry]]:
    """Gộp các cách viết khác nhau của cùng một giá trị.

    Đo trên đúng hình dạng chủ hệ thống mô tả, một cột đáng lẽ có hai nhóm bị
    đếm thành **bảy**: `Khách hàng`, `khach hang`, `KHÁCH HÀNG`, `Khách  hàng`,
    `Đại lý`, `dai ly`. Chia nhóm kiểu đó thì mọi so sánh giữa các nhóm đều sai,
    và không có gì trên màn hình nói ra điều đó.

    **Không có một từ tiếng Việt nào viết cứng trong luật này.** Nó không biết
    "khách hàng" nghĩa là gì: bỏ dấu, hạ chữ thường, gom khoảng trắng, rồi hai ô
    nào ra cùng một khoá thì là một. Luật ấy chạy y hệt trên bất cứ chữ nào.

    Bản có dấu được giữ làm tên hiển thị, vì dấu là thông tin một chiều — bỏ thì
    dễ, dựng lại thì không ai làm được.
    """
    result = frame.copy()
    diff: list[DiffEntry] = []
    for column in _target_columns(spec, frame):
        original = result[column]
        if pd.api.types.is_numeric_dtype(original):
            # Gop chu tren mot cot so la mot viec khong co nghia gi.
            continue
        present = original.notna() & (original.astype("string") != "")
        if not int(present.sum()) or _numeric_share(original[present]) >= NUMERIC_SHARE:
            # Cot so dang luu dang chu. Phep gap bo moi ky tu khong phai chu hay
            # so, nen "-1" va "1" ra cung mot khoa - do la mat du lieu, khong
            # phai gop bien the. Cot nay la viec cua cast_numeric_safe.
            #
            # Bat duoc tren du lieu that: cot `Experience` co gia tri am, va
            # luat nay de xuat gop chung vao gia tri duong cung so.
            continue
        changes = canonical_forms(str(value) for value in original[present])
        if not changes:
            continue
        for row_index in result.index[present]:
            was = str(original[row_index])
            now = changes.get(was)
            if now is None:
                continue
            # Tung o mot, co chi so dong: gop nham hai nhom that thanh mot la
            # mat du lieu, nen no phai soi nguoc duoc.
            diff.append(
                DiffEntry(
                    spec.rule_id, str(column), int(row_index), was, now, "gop ve cung mot cach viet"
                )
            )
            result.at[row_index, column] = now
    return result, diff


def cast_words_to_numbers(
    frame: pd.DataFrame, spec: RuleSpec
) -> tuple[pd.DataFrame, list[DiffEntry]]:
    """Số viết bằng chữ thành chữ số: `một` thành `1`, `hai tỷ` thành `2000000000`.

    Chỉ ghi lại dạng chữ số, **không** đổi kiểu cột — việc đổi kiểu vẫn là của
    `cast_numeric_safe`, và một chỗ đổi kiểu thì còn soi được.

    Chỉ đụng tới cột mà **gần như mọi ô** đọc lên là một con số. Điều kiện đó
    không thừa: `năm` vừa là số 5 vừa là đơn vị thời gian, và `tư` vừa là 4 vừa
    là thứ Tư. Một cột giới tính `nam`/`nữ` chỉ có một nửa số ô đọc ra số nên nó
    không bị đụng tới; một cột chỉ có đúng một giá trị cũng được bỏ qua, vì
    `nam` lặp lại từ trên xuống dưới nhiều khả năng là chữ chứ không phải số.
    """
    result = frame.copy()
    diff: list[DiffEntry] = []
    for column in _target_columns(spec, frame):
        original = result[column]
        if pd.api.types.is_numeric_dtype(original):
            continue
        present = original.notna() & (original.astype("string") != "")
        readable = int(present.sum())
        if not readable or int(original[present].nunique()) < MIN_DISTINCT:
            continue

        already = pd.to_numeric(original[present], errors="coerce").notna()
        spelled = {
            row_index: found
            for row_index in result.index[present]
            if (found := number_from_words(str(original[row_index]))) is not None
        }
        understood = int(already.sum()) + len(
            [index for index in spelled if not bool(already[index])]
        )
        if understood / readable < NUMERIC_SHARE:
            # Khong phai cot so viet bang chu. Noi ra, vi mot cot bi bo qua
            # trong im lang doc y het mot cot khong ai xet toi.
            diff.append(
                DiffEntry(
                    spec.rule_id,
                    str(column),
                    -1,
                    "giu nguyen",
                    "giu nguyen",
                    f"chi {understood}/{readable} o doc len la mot con so - cot nay khong "
                    f"phai cot so viet bang chu",
                )
            )
            continue

        for row_index, found in spelled.items():
            if bool(already[row_index]):
                continue
            was = str(original[row_index])
            diff.append(
                DiffEntry(
                    spec.rule_id, str(column), int(row_index), was, str(found), "so viet bang chu"
                )
            )
            result.at[row_index, column] = str(found)
    return result, diff


def drop_exact_duplicates(
    frame: pd.DataFrame, spec: RuleSpec
) -> tuple[pd.DataFrame, list[DiffEntry]]:
    """Drop rows that repeat an earlier row, keeping the first occurrence."""
    subset = list(spec.columns) if spec.columns else None
    if subset is not None:
        _target_columns(spec, frame)
    duplicated = frame.duplicated(subset=subset, keep="first")
    diff = [
        DiffEntry(
            spec.rule_id,
            ",".join(subset) if subset else "*",
            int(row_index),
            "dong trung lap",
            "",
            "da bo dong trung lap",
        )
        for row_index in frame.index[duplicated]
    ]
    return frame.loc[~duplicated].reset_index(drop=True), diff


def flag_missing_required(
    frame: pd.DataFrame, spec: RuleSpec
) -> tuple[pd.DataFrame, list[DiffEntry]]:
    """Mark rows missing a required value instead of dropping them.

    Dropping is a decision for a human at the gate, not for a cleaning rule.
    """
    required = _target_columns(spec, frame)
    result = frame.copy()
    missing_mask = pd.Series(False, index=result.index)
    for column in required:
        column_missing = result[column].isna() | (result[column].astype("string") == "")
        missing_mask = missing_mask | column_missing.fillna(True)
    result[MISSING_FLAG_COLUMN] = missing_mask
    diff = [
        DiffEntry(
            spec.rule_id,
            ",".join(required),
            int(row_index),
            "",
            "True",
            "thieu gia tri bat buoc",
        )
        for row_index in result.index[missing_mask]
    ]
    return result, diff


RuleFunction = Callable[[pd.DataFrame, RuleSpec], tuple[pd.DataFrame, list[DiffEntry]]]

REGISTRY: Final[Mapping[str, RuleFunction]] = {
    "trim_whitespace": trim_whitespace,
    "normalize_unicode_nfc": normalize_unicode_nfc,
    "replace_sentinel_with_null": replace_sentinel_with_null,
    "standardize_datetime": standardize_datetime,
    "cast_numeric_safe": cast_numeric_safe,
    "merge_text_variants": merge_text_variants,
    "cast_words_to_numbers": cast_words_to_numbers,
    "drop_exact_duplicates": drop_exact_duplicates,
    "flag_missing_required": flag_missing_required,
}


def apply_rules(frame: pd.DataFrame, plan: Sequence[RuleSpec]) -> CleanOutcome:
    """Run an approved plan of rules in the declared order.

    Args:
        frame: the staging frame to clean.
        plan: approved rules. RULE_ORDER decides which kind of rule runs when;
            several entries for one rule run in the order they were approved.
            The caller can never reorder the kinds, so the same plan always
            produces the same result.

    Returns:
        The cleaned frame together with the full diff log.

    Raises:
        RuleError: the plan names a rule outside the rulebook, or passes a
            parameter the rule does not read.
    """
    # Mot luat co trong REGISTRY nhung thieu trong RULE_ORDER se bi bo qua TRONG
    # IM LANG - da xay ra that voi hai luat vua them, va khong co gi bao. Hai
    # danh sach nay phai khop nhau, va cho kiem la ngay day.
    adrift = sorted(set(REGISTRY) ^ set(RULE_ORDER))
    if adrift:
        raise RuleError(
            f"Rulebook lech nhau: {adrift} khong co du trong ca REGISTRY lan RULE_ORDER. "
            "Mot luat thieu o RULE_ORDER se khong bao gio chay, va khong ai duoc bao."
        )

    unknown = [spec.rule_id for spec in plan if spec.rule_id not in REGISTRY]
    if unknown:
        known = ", ".join(RULE_ORDER)
        raise RuleError(f"Rule khong co trong rulebook: {unknown}. Chi cho phep: {known}")

    for spec in plan:
        allowed = RULE_PARAMS[spec.rule_id]
        extra = sorted(set(spec.params) - allowed)
        if extra:
            accepted = ", ".join(sorted(allowed)) or "(khong nhan tham so nao)"
            raise RuleError(
                f"Rule {spec.rule_id!r} khong nhan tham so {extra}. "
                f"Tham so hop le: {accepted}. "
                "Tham so khong duoc phep bi bo qua am tham - de xuat se hua mot hanh vi "
                "ma code khong co."
            )

    grouped: dict[str, list[RuleSpec]] = {}
    for spec in plan:
        grouped.setdefault(spec.rule_id, []).append(spec)

    rows_in = len(frame.index)
    result = frame
    diff: list[DiffEntry] = []
    applied: list[str] = []

    for rule_id in RULE_ORDER:
        for approved in grouped.get(rule_id, []):
            result, rule_diff = REGISTRY[rule_id](result, approved)
            diff.extend(rule_diff)
            applied.append(rule_id)

    return CleanOutcome(
        frame=result,
        diff=tuple(diff),
        rows_in=rows_in,
        rows_out=len(result.index),
        rules_applied=tuple(applied),
    )


def cannot_run(spec: RuleSpec) -> str:
    """Vì sao luật này chắc chắn sẽ bị từ chối, hoặc rỗng nếu chạy được.

    Cùng những điều kiện mà chính các hàm luật kiểm ngay trước khi chạy, nhưng
    hỏi được **trước** — nên một luật không thể chạy thì bị bỏ ra ngay từ đầu
    thay vì làm chết cả lượt chạy giữa chừng.

    Đã xảy ra: người dùng tích `replace_sentinel_with_null` ở ô duyệt, ô đó
    không chỉ rõ cột, và bước làm sạch chết. Trang thì không nói gì cả — họ
    ngồi nhìn một màn hình im lặng, tưởng hệ thống đang chạy.
    """
    if spec.rule_id == "replace_sentinel_with_null":
        sentinels = spec.params.get("sentinels")
        if not isinstance(sentinels, list) or not sentinels:
            return "chưa khai giá trị nào được coi là ô trống"
        if not spec.columns:
            return "chưa chỉ rõ cột — áp lên cả bảng sẽ xoá mất những số 0 có nghĩa thật"
    return ""
